### ISSUE TITLE
Request push access

### ISSUE THREAD

**Issue by ghost** [FGMEMBERS-SCENERY/Project3000#1]
Hi!
For the Kempten airport event I had to comment some objects out to don't interfere with objects in terrasync - may I get push access to upload them?
Regards

**Comment by FGDATA** [comment]
I looked for this. I found you have an standing invitation for FGMEMBERS-SCENERY group. This invitation, if accepted will give you push access to all the repos here. 

If you can't find this invitation in your inbox, let me know, and I'll re-send it.

Best, 
@IAHM-COL

**Comment by ghost** [comment]
Sry but I can't find that invitation :(

**Comment by ghost** [comment]
Okay, forget it I just found it :D 
Thanks!
