### ISSUE TITLE
Scenery

### ISSUE THREAD

**Issue by rx4** [FGMEMBERS-SCENERY/Project3000#2]
So i installed it and saw the objects and models folder. The airport building is not showing up nor is the animated jetways showing up. I went to airports all around the globe but none have the airport building. I am using windows and flightgear 2017.2. 
![fgfs-screen-001](https://user-images.githubusercontent.com/38576142/45523564-cbeefe80-b77e-11e8-9017-249c34b0ab94.png)

**Comment by rx4** [comment]
KSFO airport

**Comment by FGDATA** [comment]
@rx4 

P3000 is just one of the layers of the scenery and its supposed to be added to another scenery package, instead of used alone

A feasible alternative for an scenery already packing the P3000 is [**terraGIT**](https://github.com/FGMEMBERS-TERRAGIT/terraGIT/releases/tag/v3.2)
